config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get 'likes/create'
  get 'likes/destroy'
  devise_for :users
  root 'movies#index'
  post "/" => "movies#create"
  resources :movies
  resources :reviews
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member 
    get :followers, on: :member 
  end
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  post 'movies/:id' => "movies#show",as: "detail"
  get 'movies/:id' => "movies#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review,optional: true
  
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :reviews
    has_many :likes
    
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :movie
    has_many :likes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :reviews, dependent: :destroy
         has_many :likes, dependent: :destroy
         
         has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
         has_many :followings, through: :active_relationships, source: :follower

         has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
         has_many :followers, through: :passive_relationships, source: :following
         
         
  def already_liked?(movie)
    self.likes.exists?(movie_id: movie.id)
  end
  
  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def create
    @movie = Movie.find(params[:id])
    Like.create(user_id: current_user.id, movie_id: @movie.id)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @movie = Movie.find(params[:id])
    Like.find_by(user_id: current_user.id, movie_id: @movie.id).destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :move_to_signed_in
  require "themoviedb-api"
  # require 'rubygems'
  # require 'ruby-tmdb'
  Tmdb::Api.language("ja")
  Tmdb::Api.key("f666fc01f99324fbc4beea6ae1f0e427")
#   # setup your API key
# Tmdb.api_key = "t478f8de5776c799de5a"

# # setup your default language
# Tmdb.default_language = "en"

# @movie = TmdbMovie.find(:title => "Iron Man", :limit => 1)
# # => <OpenStruct>

# @movie.name
# # => "Iron Man"

# @movie.posters.length
# # => 12

# @movie.posters.first.data
# # => [binary blob representing JPEG]
def create
end

def index
  
end

def show 
 @like_movie = Movie.find_by(tmdb: params[:id])
  @reviews = Review.all
  @review = Review.new
  @movieinfo = JSON.parse((Tmdb::Movie.detail(params[:id])).to_json)
  
  @movie = Movie.new(title: @movieinfo["table"]["title"],
                    release_date: @movieinfo["table"]["release_date"],
                    overview: @movieinfo["table"]["overview"],
                    poster_path: @movieinfo["table"]["poster_path"],
                    tmdb: @movieinfo["table"]["id"])
  array = []
  Movie.all.each do |m|
    array << m.title
  end
   if @movieinfo["table"]["title"].in?(array)
    return
  else
    @movie.save
  end
   
end

  
  
  
  def move_to_signed_in
    unless user_signed_in?
      redirect_to  '/users/sign_in'
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to root_path
  end

  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to users_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  
def show
  @review = Review.find(params[:id])
end

def create
  @movie = Movie.find_by(params[:tmdb])
  @review = @movie.reviews.new(review_params)
  @review.user_id = current_user.id
  @review.save!
  
  redirect_to review_path(@review)
end

private
  def review_params
    params.require(:review).permit(:title,:body,:rate)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def index
    @users = User.all
  end
  
  private
  def user_params
    params.require(:user).permit(:name,:introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= javascript_include_tag 'application' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/movies/index.html.erb
  <%= link_to "マイページ" , user_path(current_user) %>
  <%= form_tag(root_path, method: :get) do %>
    <%= search_field_tag :looking_for,nil, placeholder: 'Movie Title...',value: params[:looking_for] %>
    <%= search_field_tag :page, nil, value: params[:page] %>
    <%= submit_tag '検索' %>
  <% end %>

  <%= form_tag(root_path, method: :get) do %>
    <% search_field_tag :genre,nil,value: params[:genre] %>
    <% search_field_tag :page_for, nil,value: params[:page_for] %>
    <% submit_tag '検索' %>
  <% end %>
 
  <div class="container">
    <div class="row">
      <div class="offset-3 col-6">
        <div class="border">
          <%= link_to "#アクション", "/?utf8=%E2%9C%93&genre=28&commit=%E6%A4%9C%E7%B4%A2" %>
          <%= link_to "#アドベンチャー", "/?utf8=%E2%9C%93&genre=12&commit=%E6%A4%9C%E7%B4%A2" %>
          <%= link_to "#アニメ", "/?utf8=%E2%9C%93&genre=16&commit=%E6%A4%9C%E7%B4%A2" %>
          <%= link_to "#ファミリー", "/?utf8=%E2%9C%93&genre=10751&commit=%E6%A4%9C%E7%B4%A2" %>
          <%= link_to "#ホラー", "/?utf8=%E2%9C%93&genre=27&commit=%E6%A4%9C%E7%B4%A2" %>
          <%= link_to "#ロマンス", "/?utf8=%E2%9C%93&genre=10749&commit=%E6%A4%9C%E7%B4%A2" %>
          <%= link_to "#サスペンス", "/?utf8=%E2%9C%93&genre=53&commit=%E6%A4%9C%E7%B4%A2" %>
          <%= link_to "#戦争", "/?utf8=%E2%9C%93&genre=10752&commit=%E6%A4%9C%E7%B4%A2" %>
        </div>
      </div>
    </div>
  </div>
  
<h2 class="top">Movies</h2>

<%if params[:genre].present? %>

 <% movieinfo = JSON.parse(Tmdb::Genre.movies(params[:genre], page: 1).to_json) %>
 
  <div class="container">
    <div class="row">
        <% i = 0 %>
        <% while i < movieinfo['table']['results'].count %>
          <div class="col-3">
            
            <% if movieinfo['table']['results'][i]['table']['poster_path'].present? %>
              <%= image_tag 'https://image.tmdb.org/t/p/w1280' + movieinfo['table']['results'][i]['table']['poster_path'],class: "image" %>
            <%end%>
            <div class="movie-title">
            <%if movieinfo['table']['results'][i]['table']['title'].present?%>
              <%= link_to movieinfo['table']['results'][i]['table']['title'],detail_path(movieinfo['table']['results'][i]['table']['id']) %>
            <%end%>
            </div>
            <div class="release_date">
            <%if movieinfo['table']['results'][i]['table']['release_date'].present?%>
              <%= movieinfo['table']['results'][i]['table']['release_date'] %>
            <%end%>
            </div>
           </div>
        <% i += 1%>
        <%end%>
    </div>
  </div>
  
<% elsif params[:looking_for].present? %>

  
  <% movie = JSON.parse(Tmdb::Search.movie(params[:looking_for]).to_json) %>
  <% movie["table"]["total_pages"] %>
  
  <% n = 1 %>
  <% while n <  movie["table"]["total_pages"] %>
  <% movieinfo = JSON.parse(Tmdb::Search.movie(params[:looking_for],page: n).to_json) %>
  
    <div class="container">
      <div class="row">
        <% i = 0 %>
        <% while i < movieinfo['table']['results'].count %>
         
          <div class="col-3">
           
            <% if movieinfo['table']['results'][i]['table']['poster_path'].present? %>
              <%= image_tag 'https://image.tmdb.org/t/p/w1280' + movieinfo['table']['results'][i]['table']['poster_path'],class: "image" %>
            <%end%>
             <div class="movie-title">
            <%if movieinfo['table']['results'][i]['table']['title'].present?%>
              <%= link_to movieinfo['table']['results'][i]['table']['title'],detail_path(movieinfo['table']['results'][i]['table']['id']) %>
            <%end%>
            </div>
            <div class="release_date">
            <%if movieinfo['table']['results'][i]['table']['release_date'].present?%>
              <%= movieinfo['table']['results'][i]['table']['release_date'] %>
            <%end%>
            </div>
          </div> 
        <% i += 1%>
        <%end%>
      </div>
    </div>
     <% n += 1 %>
    <% end %>
<% else %>
  
  
  
  
  
  <% @popular_movie = JSON.parse((Tmdb::Movie.popular).to_json) %>
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="slider-for">
            <%#= image_tag 'https://image.tmdb.org/t/p/original' + @popular_movie['table']['results'][3]['table']['poster_path'] %>
            <%#= image_tag 'https://image.tmdb.org/t/p/original' + @popular_movie['table']['results'][4]['table']['poster_path'] %>
            <%#= image_tag 'https://image.tmdb.org/t/p/original' + @popular_movie['table']['results'][5]['table']['poster_path'] %>
            <%#= image_tag 'https://image.tmdb.org/t/p/original' + @popular_movie['table']['results'][6]['table']['poster_path'] %>
            <%#= image_tag 'https://image.tmdb.org/t/p/original' + @popular_movie['table']['results'][8]['table']['poster_path'] %>
            <%#= image_tag 'https://image.tmdb.org/t/p/original' + @popular_movie['table']['results'][9]['table']['poster_path'] %>
            <%#= image_tag 'https://image.tmdb.org/t/p/original' + @popular_movie['table']['results'][10]['table']['poster_path'] %>
          </div>
        </div>
      </div>
    </div>
      
    <div class="slider-nav">
      <%#= image_tag 'https://image.tmdb.org/t/p/w1280' + @popular_movie['table']['results'][3]['table']['poster_path'] %>
      <%#= image_tag 'https://image.tmdb.org/t/p/w1280' + @popular_movie['table']['results'][4]['table']['poster_path'] %>
      <%#= image_tag 'https://image.tmdb.org/t/p/w1280' + @popular_movie['table']['results'][5]['table']['poster_path'] %>
      <%#= image_tag 'https://image.tmdb.org/t/p/w1280' + @popular_movie['table']['results'][6]['table']['poster_path'] %>
      <%#= image_tag 'https://image.tmdb.org/t/p/w1280' + @popular_movie['table']['results'][7]['table']['poster_path'] %>
      <%#= image_tag 'https://image.tmdb.org/t/p/w1280' + @popular_movie['table']['results'][8]['table']['poster_path'] %>
      <%#= image_tag 'https://image.tmdb.org/t/p/w1280' + @popular_movie['table']['results'][9]['table']['poster_path'] %>
      <%#= image_tag 'https://image.tmdb.org/t/p/w1280' + @popular_movie['table']['results'][10]['table']['poster_path'] %>
    </div>
  
  <% n = 1 %>
  <% while n < 3 %>
  <% @popular_movie = JSON.parse((Tmdb::Movie.popular(page: n)).to_json) %>
    <div class="container">
      <div class="row">
        
        <% i = 0%>
        <% while i < @popular_movie['table']['results'].count %>
          <div class="col-3">
            
            <% if @popular_movie['table']['results'][i]['table']['poster_path'].present? %>
              <%= image_tag 'https://image.tmdb.org/t/p/w1280' + @popular_movie['table']['results'][i]['table']['poster_path'],class: "image" %>
            <%end%>
            <div class="movie-title">
            <%if @popular_movie['table']['results'][i]['table']['title'].present?%>
              <%= link_to @popular_movie['table']['results'][i]['table']['title'], detail_path(@popular_movie['table']['results'][i]['table']['id']) %>
            <% end %>  
            </div>
            <div class="release_date">
            <%if @popular_movie['table']['results'][i]['table']['release_date'].present?%>
              <%= @popular_movie['table']['results'][i]['table']['release_date'] %>
            <%end%>
            </div>
          </div>
        <% i += 1%>
        <%end%>
      </div>
    </div>
    <% n += 1 %>
    <% end %>
<% end %>
    
  Copyright（c）2015 18Months Srl

app/views/movies/search.html.erb
     <h1>映画検索!!</h1>

<div>
  <%= form_tag(root_path, method: :get) do %>
    <%= search_field_tag :looking_for,nil, placeholder: 'Movie Title...',value: params[:looking_for] %>
    <%= submit_tag '検索' %>
  <% end %>
  
  <% form_tag(root_path, method: :get) do %>
    <% search_field_tag :looking,nil, placeholder: 'Movie Title...',value: params[:looking] %>
    <% submit_tag '検索' %>
  <% end %>
</div>
<%if params[:looking].present? %>
 <% movie = JSON.parse((Tmdb::Genre.movies(params[:looking])).to_json) %>
    <h2><%= params[:looking] %>の検索結果</h2>
    <% movieinfo = JSON.parse((Tmdb::Genre.movies(params[:looking],page: params[:page_for])).to_json) %>
     =====================
    <% i = 0 %>
    <div class="card-wrapper">
        <% while i < movie['table']['results'].count %>
            <div class="card">
                <div class="card-upperinfo">
                    <%if movie['table']['results'][i]['table']['title'].present?%>
                        <h3><%= link_to movie['table']['results'][i]['table']['title'],detail_path(movie['table']['results'][i]['table']['id']) %></h3>
                    <%end%>
                    <% if movie['table']['results'][i]['table']['release_date'].present? %>
                        <p class="release-date"><%= movie['table']['results'][i]['table']['release_date'] %></p>
                    <%end%>
      </div>
                <% if movie['table']['results'][i]['table']['poster_path'].present? %>
                    <p><%= image_tag 'https://image.tmdb.org/t/p/w1280' + movie['table']['results'][i]['table']['poster_path'],class: "card-img" %></p>
                <%end%>
                
                <% if movie['table']['results'][i]['table']['overview'].present? %>
                    <p><%= movie['table']['results'][i]['table']['overview'] %></p>
                <%end%>
                
            </div>
            <% i += 1%>
        <%end%>
    </div>
<% end %>
<%= link_to "ホラー", "https://daae3ff7e70e4330be108db28209145d.vfs.cloud9.us-east-1.amazonaws.com/?utf8=%E2%9C%93&looking=18&commit=%E6%A4%9C%E7%B4%A2" %>


<%if params[:looking_for].present? %>
    <% movieinfo = JSON.parse((Tmdb::Search.movie(params[:looking_for])).to_json) %>
    <h2><%= params[:looking_for] %>の検索結果</h2>
    <% movieinfo = JSON.parse((Tmdb::Search.movie(params[:looking_for],page: params[:page_for])).to_json) %>
    =====================
    <% i = 0 %>
    <div class="card-wrapper">
        <% while i < movieinfo['table']['results'].count %>
            <div class="card">
                <div class="card-upperinfo">
                    <%if movieinfo['table']['results'][i]['table']['title'].present?%>
                        <h3><%= link_to movieinfo['table']['results'][i]['table']['title'],detail_path(movieinfo['table']['results'][i]['table']['id']) %></h3>
                    <%end%>
                    <% if movieinfo['table']['results'][i]['table']['release_date'].present? %>
                        <p class="release-date"><%= movieinfo['table']['results'][i]['table']['release_date'] %></p>
                    <%end%>
      </div>
                <% if movieinfo['table']['results'][i]['table']['poster_path'].present? %>
                    <p><%= image_tag 'https://image.tmdb.org/t/p/w1280' + movieinfo['table']['results'][i]['table']['poster_path'],class: "card-img" %></p>
                <%end%>
                
                <% if movieinfo['table']['results'][i]['table']['overview'].present? %>
                    <p><%= movieinfo['table']['results'][i]['table']['overview'] %></p>
                <%end%>
                
            </div>
            <% i += 1%>
        <%end%>
    </div>
<%else%>
    <h2>本日の世界のトレンド</h2>
    ====================
    <% movieinfo = JSON.parse((Tmdb::Movie.popular).to_json) %>
    <% i = 0 %>
    <div class="card-wrapper">
        <% while i < movieinfo['table']['results'].count %>
            <div class="card">
                <div class="card-upperinfo">
                    <%if movieinfo['table']['results'][i]['table']['title'].present?%>
                        <h3><%= link_to movieinfo['table']['results'][i]['table']['title'], detail_path(movieinfo['table']['results'][i]['table']['id'])%></h3>
                    <%end%>
                        <% if movieinfo['table']['results'][i]['table']['release_date'].present? %>
                        <p class="release-date"><%= movieinfo['table']['results'][i]['table']['release_date'] %></p>
                    <%end%>
                </div>

                <% if movieinfo['table']['results'][i]['table']['poster_path'].present? %>
                    <p><%= image_tag 'https://image.tmdb.org/t/p/w1280' + movieinfo['table']['results'][i]['table']['poster_path'],class: "card-img" %></p>
                <%end%>
            </div>

            <% i += 1%>
        <%end%>
    </div>
<%end%>
Copyright（c）2015 18Months Srl

app/views/movies/show.html.erb
<% detail = JSON.parse((Tmdb::Movie.detail(params[:id])).to_json) %>
  <div class="container">
    <div class="row">
      <div class="col-4">
     
        <%if detail['table']['poster_path'].present?%>
          <%= image_tag 'https://image.tmdb.org/t/p/w1280' + detail['table']['poster_path'], class: "image" %>
        <%end%>
        <%if detail['table']['title'].present?%>
          <h4><%= detail['table']['title'] %></h4>
        <%end%>
        
        
        <% array = [] %>
        <% @reviews.each do |r| %>
          <% if r.movie.tmdb == @movieinfo["table"]["id"] %>
            <% array << r.rate %>
          <% end %>
        <% end %>
        <% unless array.empty? %>
        <h2>平均<%= (array.sum / array.count).round(2).to_f %>点</h2>
      <% end %>
      
      </div>
      
      <div class="col-8">
        <%if detail['table']['overview'].present?%>
          <%= detail['table']['overview'] %>
        <%end%>
    
        <%= form_with model: @review, local: true do |f| %>
          <div id="evaluate_stars">
            <%= f.hidden_field :rate, id: :evaluate_stars %>
            <label>評価</label>
          </div>
          <script>
             $('#evaluate_stars').raty({
              half: true,
              starOn: "<%= asset_path('star-on.png') %>",
              starOff: "<%= asset_path('star-off.png') %>",
              starHalf: "<%= asset_path('star-half.png') %>",
              scoreName: 'review[rate]' 
            }); 
          </script>

          <%= f.text_field :title %>
          <%= f.text_area :body %>
          <%= f.submit %>
          <% end %>
      </div>
    </div>



  <div class="row">
    <div class="offset-3 col-6">
      <% Movie.all.each do |m| %>
        <% if m.tmdb == @movieinfo["table"]["id"] %>
        <% m.reviews.each do |r| %>
          <%= r.user.name %>
          <%= link_to r.title, review_path(r.id) %>
          <%= r.body %>
        <% end %>
      <% end %>
      <% end %>
    </div>
  </div>
</div>



 <h2><% if current_user.already_liked?(@like_movie) %>
  <%= link_to "取り消し", destroy_like_path(@like_movie), method: :DELETE%>
<% else %>
  <%= link_to '保存', create_like_path(@like_movie), method: :POST %>
<% end %></h2>


Copyright（c）2015 18Months Srl

app/views/relationships/create.html.erb
<h1>Relationships#follower_id:integer</h1>
<p>Find me in app/views/relationships/follower_id:integer.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#following_id:integer</h1>
<p>Find me in app/views/relationships/following_id:integer.html.erb</p>

app/views/reviews/show.html.erb
<div class="movie-evaluation" data-score="<%= @review.rate %>"></div>

<script>
  $('.movie-evaluation').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<%= @review.movie.title %>
<%= @review.movie.release_date %>
<%= @review.movie.overview %>
<%= image_tag 'https://image.tmdb.org/t/p/w1280' + @review.movie.poster_path, class: "image" %>

<%= @review.title %>
<%= @review.body %>

app/views/users/edit.html.erb
<%= form_for(current_user) do |f| %>
<%= f.text_field :name %>
<%= f.text_area :introduction %>
<%= f.submit %>
<% end %>

app/views/users/followers.html.erb
<% @users.each do |user| %>
  <hr>
  <p><span>email: </span><%= link_to user.email, user_path(user.id) %></p>
    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>
<% end %>

app/views/users/follows.html.erb
<% @users.each do |user| %>
  <hr>
  <p><span>email: </span><%= link_to user.email, user_path(user.id) %></p>
    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |u| %>
<%= link_to u.name, user_path(u.id) %>
<% end %>

app/views/users/show.html.erb
<%= link_to "sign_out" ,  destroy_user_session_path, method: :delete %>

<div class="container">
  <div class="row">
    <div class="col-4">
      <table class="table">
        <thead>
          <th>Name</th>
          <th>Introduction</th>
          <th></th>
          <th></th>
          <th></th>
        </thead>
        <tbody>
          <td><%= @user.name %></td>
          <td><%= @user.introduction %></td>
          <tr>
            <td><%=link_to "フォロー", follows_user_path(@user.id) %>:<%= @user.followings.count %></td>
          <td><%=link_to "フォロワー", followers_user_path(@user.id) %>:<%= @user.followers.count %></td>
          </tr>
          
          <% if current_user != @user %>
        <% if @user.followed_by?(current_user) %>
            <td><%=link_to "フォロー済み", user_relationships_path(@user.id), method: :delete %></td>
        <% else %>
            <td><%=link_to "フォローする", user_relationships_path(@user.id), method: :post %></td>
        <% end %>
    <% end %>
        </tbody>
      </table>
    </div>
  
  <div class="col-8">
    <table class="table">
      <thead>
        <th>レビュー一覧！！</th>
        <th></th>
        <th></th>
        <th></th>
      </thead>
      <tbody>
        
        <% @user.reviews.each do |r| %>
        <tr>
        <td><<%= r.movie.title %>></td>
        <td><%= image_tag 'https://image.tmdb.org/t/p/w1280' + r.movie.poster_path , class: "review_image" %></td>
        <td><%= r.title %></td>
        <td><%= r.body %></td>
        </tr>
        <% end %>
        
      </tbody>
    </table>
    
    
  </div>
  </div>





<table class="table">
  <thead>
    <th>保存したもの</th>
    <th></th>
  </thead>
  <tbody>
    <% @user.likes.each do |l| %>
    <tr>
      <td><%= image_tag 'https://image.tmdb.org/t/p/w1280' + l.review.movie.poster_path, class: "review_image" %></td>
      <td><<%= l.review.movie.title %>></td>
    </tr>
    <% end %>
  </tbody>
</table>




<%= link_to "edit", edit_user_path(@user) %>
<%= link_to "/", root_path %>

</div>